catalyst:
  files:
  - this/file
  - that/file
  syscalls:
  - this_call
  - that_call
  sys_args:
  - call: this_call
    arg_pos: 0
    arg_vals:
    - this_arg1
    - this_arg2
  - call: that_call
    arg_pos: 0
    arg_vals:
    - that_arg1
    - that_arg2
product:
  init:
  - this_opt
  - that_opt
  kernel:
  - CONFIG_THIS
  - CONFIG_THAT
