catalyst:
  files:
  - this/file
  - that/file
  sockets:
    - THIS_SOCK_TYPE
    - THAT_SOCK_TYPE
  syscalls:
  - this_call
  - that_call
product:
  init:
  - this_opt
  - that_opt
  kernel:
  - CONFIG_THIS
  - CONFIG_THAT
